<template>
    <section>
        <!--工具条-->
        <el-col :span="24" class="toolbar" style="padding-bottom: 0px;">
            <el-form :inline="true" :model="filters">
                <el-form-item style="float: right">
                    <el-button type="primary" v-on:click="goBack">返回</el-button>
                </el-form-item>
            </el-form>
        </el-col>

        <div v-html="noticeInfo"></div>

    </section>
</template>

<script>
    export default {
        name: "",
        data() {
            return {
                noticeInfo: "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><strong style=\"margin: 0px; padding: 0px;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">一、招标编号：</span></strong><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">JWC/H-20170816-056</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><strong style=\"margin: 0px; padding: 0px;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">二、项目概况：</span></strong></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;1.项目地点：江苏建筑职业技术学院内。</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;2.招标范围：</span><span style=\"margin: 0px; padding: 0px; text-decoration-line: underline; background: none !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\"><span style=\"margin: 0px; padding: 0px; background: none !important;\">服务器</span>4台</span></span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">（详见招标文件）</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><strong style=\"margin: 0px; padding: 0px;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">三、投标人资质要求：</span></strong></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;1、具有独立法人资格、企业法人营业执照；</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;2、有销售同样产品的业绩；</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;3、投标单位应独立参与投标；</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;4、具有良好的企业资信，近年无不良业绩，并自愿遵守招标须知的厂家；</span></p>\n" +
                "<p style=\"margin: 0px 0px 0px 28px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">5、</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">相关产品生产、销售、代理资质；</span></p>\n" +
                "<p style=\"margin: 0px 0px 0px 28px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">6、具有一定的经营规模，注册资金人民币100万元以上（含100万元）。</span></p>\n" +
                "<p style=\"margin: 0px 0px 0px 28px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">7</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">、详见招标文件。</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><strong style=\"margin: 0px; padding: 0px;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">四、资格审查方式及办法：</span></strong></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;1.本项目实行资格后审，招标人不予电话通知，资格条件审查在投标时进行。</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;2.满足资格条件并进行投标工作的投标人应在2017年</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">8</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">月</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">29</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\"><span style=\"margin: 0px; padding: 0px; background: none !important;\">日</span>17:00时前填写的&ldquo;投标人报名表&rdquo;以word格式发送至招标人jianyuanzhaobiao@163.com邮箱。</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 1.7; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><strong style=\"margin: 0px; padding: 0px;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">五、投标文件及有关费用：</span></strong></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;1.招标文件售价：本项目收取标书费200元，送达投标文件时现金缴纳，售后不退（标书费收取在投标时进行）。</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;2.投标保证金：统一收取投标保证金为</span><span style=\"margin: 0px; padding: 0px; text-decoration-line: underline; background: none !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">5000</span></span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">元，在送达投标文件时缴纳。收取方式为现金（自带信封，现场封装）。</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 1.7; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><strong style=\"margin: 0px; padding: 0px;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">六、接受投标文件时间及地点：</span></strong></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;1.接受投标文件时间:开标前半小时。</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 32px; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;2.接受投标文件地点:江苏建筑职业技术学院行政楼4楼403室。</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 1.7; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><strong style=\"margin: 0px; padding: 0px;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">七、开标时间及地点：</span></strong></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 1.7; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">&nbsp;&nbsp;&nbsp;&nbsp;2017年</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">9</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">月</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">6</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\"><span style=\"margin: 0px; padding: 0px; background: none !important;\">日</span>1</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">5</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">:</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">0</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">0，江苏建筑职业技术学院行政楼4楼403室公开开标。届时请参加投标的单位法定代表人或其授权委托人准时参加。</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 1.7; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><strong style=\"margin: 0px; padding: 0px;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">八、澄清与答疑：</span></strong></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 1.7; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; text-indent: 32px; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">1.招标文件的修改、补充和答疑文件将在招标人网站上以公告的形式发布，请投标人自行查看。</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 1.7; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><strong style=\"margin: 0px; padding: 0px;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">九、联系方式：</span></strong></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 1.7; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; text-indent: 32px; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\"><span style=\"margin: 0px; padding: 0px; background: none !important;\">报名咨询</span><span style=\"margin: 0px; padding: 0px; background: none !important;\">张老师</span><span style=\"margin: 0px; padding: 0px; background: none !important;\">电话：</span>0516&mdash;83996343</span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 1.7; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; text-indent: 32px; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">项目咨询</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; text-decoration-line: underline; background: none !important;\">荣老师</span><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">电话：</span><span style=\"margin: 0px; padding: 0px; text-decoration-line: underline; background: none !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\">15050823727</span></span></p>\n" +
                "<p style=\"margin: 0px; padding: 0px; background-color: #f2f2f2; line-height: 1.7; font-size: 15px; color: #333333; font-family: 'Microsoft YaHei', helvetica, verdana, san-serif; text-indent: 32px; background-image: none !important; background-position: initial !important; background-size: initial !important; background-repeat: initial !important; background-attachment: initial !important; background-origin: initial !important; background-clip: initial !important;\"><span style=\"margin: 0px; padding: 0px; font-family: 仿宋; font-size: 16px; background: none !important;\"><span style=\"margin: 0px; padding: 0px; background: none !important;\">监督电话：</span>0516&mdash;83996085</span></p>"
            }
        },
        methods:{
            goBack(){
                this.$router.back(-1);
            }
        }
    }
</script>

<style scoped>

</style>